---
title: "Education & Experience"
---

<br>

## Education

### PhD in Clinical Translational Science
**Case Western Reserve University** | Cleveland, Ohio | 2025 - Present


### Master of Science in Respiratory Care
**Rush University** | Chicago, Illinois | 2021 - 2023

- GPA 4/4 
- Thesis: 
Albuainain FA, Li J. Aerosol delivery to simulated spontaneously breathing tracheostomized adult model with and without humidification. Respir Care. 2024;69(7):847-853. DOI: 10.4187/respcare.11495

### Bachelor of Science in Respiratory Care 
**Imam Abdulrahman Bin Faisal University** | Dammam, Saudi Arabia | 2012 - 2016

- GPA: 4.74 / 5 
- Capstone: 
Alwohayeb NS, Alenazi BA, Albuainain FA, Alrayes MM. A comparison between two types of resistive inspiratory muscle training devices in normal subjects in regard to pulmonary functions. Int J Phys Med Rehabil. 2018;6(1):100044. DOI: 10.4172/2329-9096.1000449

---


## Professional Experience

### Lecturer
**Imam Abdulrahman Bin Faisal University - College of Applied Medical Science** | Jubail, Saudi Arabia | 2018 - Present

- Teach undergraduate respiratory care courses, including Therapeutics, Neonatal & Pediatric RC, Pulmonary Rehabilitation, and Medical Gases.
- Supervise student research projects
- Coordinate simulation-based training for clinical procedures.
- Skills utilized: Curriculum design, mentor-ship, academic advising.

### Regestered Respiratory Therapist
**King Fahad Specialist Hospital** | Dammam - Saudi Arabia | 2017 - 2018

- Provide patient-centered respiratory care in critical settings.
- Manage mechanical ventilation, aerosol therapy, and airway care.

---


## Research Experience

### Current Research Projects
**Cleveland Clinic Foundation** | Dr. Vickram Tejwani | 2025-Present
- Timely Treatment Escalation After Recurrent Asthma Exacerbations
- Asthma patient quality of life and barriers to asthma control. 

### Previous Research Projects
**Rush University** | Dr. Jie Li | 2021-2025

- **Albuainain FA**, Man X, Li J.Aerosol Delivery to Simulated Spontaneously Breathing Tracheostomized Children's Models with High-Flow Tracheal Oxygen. Respir Care. Published online August 25, 2025. doi:10.1177/19433654251360623
-	**Albuainain FA**, Man X, Alamoudi O, Li J. Factors influencing aerosol delivery during invasive ventilation. Respir Care. Published online July 2, 2025. DOI: 10.1089/respcare.12942
- **Albuainain FA**, Almomen A, Gong L, Li J. Quantification of health care worker model to secondhand exposure of aerosols during nebulization treatment. Respir Care. DOI: 10.1089/respcare.12668
-	Chen X, **Albuainain FA**, Li J. Aerosol delivery to simulated spontaneously breathing tracheostomized adult patients with heated humidified high flow oxygenation. Respir Care. 2025;70(7):873–878. DOI:  10.1089/respcare.12467
-	Li J, Lyu S, Luo J, Liu P, **Albuainain FA**, Alamoudi OA, Rochette V, et al. Prophylactic antibiotics delivered via the respiratory tract to reduce ventilator-associated pneumonia: a systematic review, network meta-analysis, and trial sequential analysis. Crit Care Med. 2024;52(10):1612-1623. DOI: 10.1097/CCM.0000000000006323
-	Liu P, Lyu S, Mireles-Cabodevila E, Miller AG, **Albuainain FA**, et al. Survey of ventilator waveform interpretation among ICU professionals. Respir Care. 2024;69(7):773-781. DOI: 10.4187/respcare.11677
-	Li J, Abulkhair RR, **Albuainain FA**. A pediatric bench model of continuous albuterol delivery using heliox. Respir Care. 2024;69(12):1517-1522. DOI: 10.4187/respcare.11713
-	**Albuainain FA**, Li J. Aerosol delivery to simulated spontaneously breathing tracheostomized adult model with and without humidification. Respir Care. 2024;69(7):847-853. DOI: 10.4187/respcare.11495
-	Li J, Deng N, He WJ, Yang C, Liu P, **Albuainain FA**, et al. The effects of flow settings during high-flow nasal cannula oxygen therapy for neonates and young children. Eur Respir Rev. 2024;33(230223):14. DOI: 10.1183/16000617.0223-2023
-	Li J, **Albuainain FA**, Tan W, Scott JB, Roca O, Mauri T. The effects of flow settings during high-flow nasal cannula support for adult subjects: a systematic review. Crit Care. 2023;27(1):78. DOI: 10.1186/s13054-023-04361-5

---


## Awards and Honors

-	2025, Young Investigator Award – American Association of Respiratory Care.
-	2023, Research Excellence Award – Rush University 
-	2023, Recipient of the graduate assistance in research scholarship – Rush University
-	2023, Acknowledged on the Dean's List for academic excellence. – Rush University
-	2023, Nominated for the Lambda Beta Society by the Respiratory Care Department in recognition of academic excellence and an impeccable ethical record
-	2022, Recipient of academic excellence award from the Coalition for Baccalaureate and Graduate Respiratory Therapy Education (CoBGRTE)  
-	2022, Recipient of research proposal award from the Coalition for Baccalaureate and Graduate Respiratory Therapy Education (CoBGRTE) 
-	2016, Awarded first place in the respiratory care intellectual competition at the 2nd PSMCH Respiratory Care Students Symposium 
- 2015, Awarded first place in the general intellectual student competition at Imam Abdulrahman bin Faisal University 

---

## Download My CV

**[Click here to download my full CV](cv.pdf)**
